# configs/pcad_test_config.yaml
# Configuração para um teste rápido de sanidade no ambiente do PCAD.

model_params:
  num_classes: 200

train_params:
  epochs: 1          # Apenas 1 época para um teste rápido
  batch_size: 8      # Batch size pequeno para não sobrecarregar a memória
  learning_rate: 0.001

inference_params:
  batch_size: 16     # Batch size para a fase de inferência/validação
