# configs/mobilenet_V1_config.yaml
# Configuração para os experimentos finais com o modelo MobileNet V1 no PCAD.  

model_params:
  num_classes: 200

train_params:

  epochs: 100
  batch_size: 128
  learning_rate: 0.001

inference_params:
  batch_size: 128