# configs/pcad_final_config.yaml
# Configuração para os experimentos finais e coleta de resultados no PCAD.

model_params:
  num_classes: 200

train_params:

  epochs: 10
  batch_size: 64
  learning_rate: 0.001

inference_params:
  batch_size: 128
