# configs/resnet34_config.yaml
# Configuração para os experimentos finais com o modelo ResNet34 no PCAD.

model_params:
  num_classes: 200

train_params:

  epochs: 100
  batch_size: 32
  learning_rate: 0.001

inference_params:
  batch_size: 32